### ISSUE TITLE
buyer -> plant -> farmer ... farmer -> plant

### ISSUE THREAD

**Issue by chontipan** [pchaow/TMMulbery#5]
buyer ->
 - plant
 - farmer

farmer -> plant

**Comment by chontipan** [comment]
buyer->plant
จำนวนรายการในหน้า plant index
![image](https://user-images.githubusercontent.com/9138402/28751120-680f3e90-7529-11e7-91fa-9d6a95c4a10b.png)

**Comment by chontipan** [comment]
buyer->plant
- set default ตำแหน่งที่เพียรกุศล ตอนสร้างแปลง
- ตอนแก้ไขให้ default map ตำแหน่งที่ปักไว้

**Comment by pchaow** [comment]
วิธีแก้
1. หาพิกัดตำแหน่งเพียรกุศล
2. นำพิกัดไปแก้ ใน default ใน PlantEdit.vue / PlantCreate.vue

**Comment by chontipan** [comment]
แก้ไขละครับ
