### ISSUE TITLE
เลือกจังหวัดแล้วอำเภอไม่โหลดตาม ในตอนสร้างแปลง กับแก้ไขแปลง

### ISSUE THREAD

**Issue by chontipan** [pchaow/TMMulbery#6]
เลือกจังหวัดแล้วอำเภอไม่โหลดตาม ในตอนสร้างแปลง กับแก้ไขแปลง

**Comment by pchaow** [comment]
ใครสร้างอะท่าน

**Comment by chontipan** [comment]
ของทั้ง buyer สร้าง+แก้ไขเอง กับของทั้ง farmer สร้าง+แก้ไขเลยอ่ะท่าน

**Comment by pchaow** [comment]
โอเค แก้ละ ปัญหาเกิดจากระบบ isLocked อ่ะ เดี๋ยวจะ push code
