### ISSUE TITLE
ระยะทางจากเพียรกุศล ในหน้า ChildrenPlant.vue ไม่ขึ้น

### ISSUE THREAD

**Issue by chontipan** [pchaow/TMMulbery#7]
ระยะทางจากเพียรกุศล ในหน้า ChildrenPlant.vue ไม่ขึ้น

**Comment by pchaow** [comment]
![image](https://user-images.githubusercontent.com/5770600/28927369-8e2846d0-7894-11e7-965b-f412e3a8b064.png)
